# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170217_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='Date de publication')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='ReponseQuestionnaires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Anonyme', max_length=50)),
                ('date', models.DateTimeField(verbose_name='Date de reponse')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='ReponseQuestionQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('reponse', models.CharField(max_length=200)),
                ('reponse_questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ReponseQuestionnaires')),
            ],
        ),
    ]
