# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_questionnaire_questionquestionnaire_reponsequestionnaires_reponsequestionquestionnaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionquestionnaire',
            old_name='question_text',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='reponsequestionquestionnaire',
            old_name='question_text',
            new_name='question',
        ),
    ]
